# Generated by Django 4.1.2 on 2022-10-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=None),
        ),
    ]
