# Generated by Django 4.1.2 on 2022-10-12 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_candidate_slot_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='interview_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
