# Generated by Django 4.1.2 on 2022-10-12 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_slot_end_time_alter_slot_interview_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Interview',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
